spring.application.name=cinemaclub-api

# ===== BANCO DE DADOS =====
spring.datasource.url=jdbc:postgresql://localhost:5432/cinemaclubdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# ===== FLYWAY =====
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===== JWT =====
jwt.secret=minha-chave-secreta-super-segura-para-cinemaclub-api-2024
jwt.expiration=900000
jwt.refresh-expiration=604800000

# ===== SWAGGER =====
springdoc.swagger-ui.path=/swagger-ui.html
